
server:  port: 8080
  servlet:    context-path: /
    
spring:  datasource:    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql

mybatis-plus:  type-aliases-package: com.tianya.springboot.mybatis.plus.entity
  config-location: classpath:mybatis/mybatis.xml
  