package com.tianya.springboot.mybatis.mapper;

import com.tianya.springboot.mybatis.entity.DeptBean;

public interface DeptBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    int deleteByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    int insert(DeptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    int insertSelective(DeptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    DeptBean selectByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    int updateByPrimaryKeySelective(DeptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    int updateByPrimaryKey(DeptBean record);
}