package com.tianya.springboot.mybatis.mapper;

import com.tianya.springboot.mybatis.entity.UserBean;

public interface UserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Tue Dec 22 09:05:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Tue Dec 22 09:05:07 CST 2020
     */
    int insert(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Tue Dec 22 09:05:07 CST 2020
     */
    int insertSelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Tue Dec 22 09:05:07 CST 2020
     */
    UserBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Tue Dec 22 09:05:07 CST 2020
     */
    int updateByPrimaryKeySelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Tue Dec 22 09:05:07 CST 2020
     */
    int updateByPrimaryKey(UserBean record);
}