package com.tianya.springboot.mybatis.mapper;

import com.tianya.springboot.mybatis.entity.UserBean;

public interface UserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sat Jan 09 13:59:20 CST 2021
     */
    int insert(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sat Jan 09 13:59:20 CST 2021
     */
    int insertSelective(UserBean record);
}