

server:  port: 8080
  servlet:    context-path: /
    
    
spring:  redis:    host: localhost
    port: 6379
    jedis:      pool:        max-active: 10
        max-idle: 8
        min-idle: 4
        max-wait: 1000


