

# DBTAB 分库分表 配置


spring:
  shardingsphere:
    datasource:
      # 配置数据库名称
      names: db1
      # 配置具体数据库连接信息
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: mysql
    sharding:
      tables:
        t_order:
          keyGenerator:
            column: order_id
            type: SNOWFLAKE
            
          actualDataNodes: db1.t_order_$->{1..2}
          tableStrategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 2 + 1}
        
    props:
      sql.show: true
      

  main:
    allow-bean-definition-overriding: true
   