
server:  port: 8080
  servlet:    context-path: /
    
#freemarker的配置
spring:
  freemarker:    cache: false
    charset: UTF-8
    content-type: text/html; charset=utf-8
    prefix: /
    suffix: .html
    #  mvc:#    view:#      prefix: /
#      suffix: .html
#      
logging:  level:    root: debug