package com.tianya.springboot.mybatis.entity;

public class DeptBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptId
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptName
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    private String deptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptAddress
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    private String deptaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptId
     *
     * @return the value of dept.deptId
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptId
     *
     * @param deptid the value for dept.deptId
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptName
     *
     * @return the value of dept.deptName
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptName
     *
     * @param deptname the value for dept.deptName
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptAddress
     *
     * @return the value of dept.deptAddress
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    public String getDeptaddress() {
        return deptaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptAddress
     *
     * @param deptaddress the value for dept.deptAddress
     *
     * @mbggenerated Mon Oct 04 20:18:28 CST 2021
     */
    public void setDeptaddress(String deptaddress) {
        this.deptaddress = deptaddress == null ? null : deptaddress.trim();
    }
}