
server:  port: 8080
  servlet:    context-path: /
    
spring:  application:    name: feign-learn
    
logging:  level:    root: debug
    sun.rmi: error
    org.apache.tomcat: error
    
    
student:
  feign:
    url: http://localhost:8081/api/v1/student