

server:
  port: 8080
  servlet:
    context-path: /
    
  tomcat:
    uri-encoding: UTF-8
    
spring:
  messages:
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
      
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      
      
      
logging:  level:    root: info
    
    
        